name: tfsec
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tfsec:
    name: tfsec
    runs-on: self-hosted

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
    
      - name: Install tfsec
        run: |
            VERSION=$(curl -s "https://api.github.com/repos/aquasecurity/tfsec/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
            URL="https://github.com/aquasecurity/tfsec/releases/download/${VERSION}/tfsec-linux-arm64"
            curl -L "${URL}" -o tfsec
            chmod +x tfsec
            sudo mv tfsec /usr/local/bin/
    
      - name: Run tfsec (high/critical)
        run: tfsec --severity HIGH --severity CRITICAL
  
      - name: Run tfsec (medium/low)
        run: |
            tfsec --severity MEDIUM --severity LOW || true
